FROM nvcr.io/nvidia/tensorrt:23.05-py3

# Set up environment
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
ENV PIP_INSTALL="python -m pip --no-cache-dir install --upgrade"

# Install system libraries
RUN apt-get update && \
    apt-get install -y \
        libgl1-mesa-glx \
        protobuf-compiler \
        libprotoc-dev \
        libb64-0d \
        libturbojpeg \
        python3-opencv \
        ffmpeg && \
    rm -rf /var/lib/apt/lists/*

# Set working directory inside the container
WORKDIR /workspace

# Copy requirements and install Python dependencies
COPY src/requirements.txt .
RUN $PIP_INSTALL -r requirements.txt
RUN $PIP_INSTALL cupy-cuda12x pynvjpeg

# Copy all necessary code
COPY src/api_trt ./api_trt
COPY main.py .

# Start the main script (designed for RunPod Serverless input)
CMD ["python3", "main.py"]